image: node:10-alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  except:
    - /^release.*$/
    - /^feature.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
  before_script:
    - yarn
  script:
    - yarn run build

test:
  stage: test
  except:
    - /^release.*$/
    - /^feature.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
  before_script:
    - yarn
  script:
    - yarn run test
